# Generated by Django 4.2.1 on 2023-09-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_feedback_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('N', 'New feedback'), ('P', 'Feedback in process'), ('F', 'Feedback was finished')], default='N', max_length=1, verbose_name='Feedback status'),
        ),
    ]
